### ISSUE TITLE
How can ewe find the read and write success 

### ISSUE THREAD

**Issue by karanariel** [ederdoski/SimpleBle#1]

**Comment by ederdoski** [comment]
i'm sorry for the late reply, hope what this response can help other developers, you need check the method onBleWrite this callback have a parameter called status, this variable have the value of your response.

common responses codes: 

* GATT_SUCCESS = 0
* GATT_FAILURE = 257
* GATT_READ_NOT_PERMITTED = 2
* GATT_WRITE_NOT_PERMITTED = 3

In this link do you have more information over the status codes: 

https://developer.android.com/reference/android/bluetooth/BluetoothGatt

For more help please check de folder ExampleApp in the repo.
